spring:
  datasource:
    url: jdbc:mysql://record-collector-db.c5zsdjg2ykre.us-east-2.rds.amazonaws.com:3306/record_collector
    username: admin
    password: BdSeJFkxSxdOloE0aBEV
  jpa:
    hibernate.ddl-auto: update
    hibernate.generate-ddl: true
    hibernate.show-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG